# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD013: Line length
MD013:
  line_length: 200
  code_blocks: false
  tables: false

# MD025: Multiple top level headings
MD025: false

# MD040: Fenced code language
MD040: false
